### ISSUE TITLE
License list deploys failing

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#2006]
We're now seeing [the following error](https://github.com/spdx/license-list-XML/actions/runs/5237415498) from [deploy.yaml](https://github.com/spdx/license-list-XML/blob/main/.github/workflows/deploy.yaml) on build:

<img width="1319" alt="image" src="https://github.com/spdx/license-list-XML/assets/678569/37673039-7c5d-400c-99b7-6bd4c7d91974">

@goneall I'm not that familiar with GitHub Actions, but it looks like this might be fixable by bumping `actions/setup-java` and `actions/checkout` to v3 -- see https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/ and https://github.com/actions/setup-java#basic-configuration.

Does that look right to you? If so, I can submit a PR to see if that addresses this. I don't _think_ there's anything with the License List Publisher itself that's relevant here but just wanted to get your thoughts. Thanks!

**Comment by goneall** [comment]
@swinslow From looking at the error messages, updating the action versions looks like it should fix it.  As far as I know we don't depend on anything version specific - so please give it a try.

**Comment by swinslow** [comment]
It didn't fully fix it:

<img width="462" alt="image" src="https://github.com/spdx/license-list-XML/assets/678569/73abe15a-acec-4f51-b5e8-920482f6fd63">

Now requires a value for `distribution` for one of the [supported distributions](https://github.com/actions/setup-java#supported-distributions).

Looks like `temurin` is perhaps a good choice? I'll go with that for the moment...
